theme: jekyll-theme-midnight
title: Welcome to the Old Man's Homepage
description: Fell free to bookmark if you have reached terminal boardom.
# Hello
# About
# Education
## BSc. Colorado School of Mines - Geological Engineering
##
# What I have done
